### ISSUE TITLE
it won't let me create an account

### ISSUE THREAD

**Issue by manzi2009** [rune/rune#145]
Everything works but when he finished saying when I was born he gives me the captha I do it right and he tells me to try it again and when I try it again the same thing happens to me

**Comment by manzi2009** [comment]
> Everything works but when he finished saying when I was born he gives me the captha I do it right and he tells me to try it again and when I try it again the same thing happens to me

**Comment by bfelbo** [comment]
Sorry to hear that you're having issues! This sounds like a problem with the Rune app, not the SDK (which is used to make games for Rune). This GitHub repo is for issues related to to the SDK only.

Can you write feedback@rune.ai with your Rune username and we'll help you there? :)
