### ISSUE TITLE
Broken links to docs in readme

### ISSUE THREAD

**Issue by ledenis** [rune/rune#176]
Hi, just wanted to report that the docs links from the readme seem broken:

- [Intro](https://developers.rune.ai/docs/multiplayer/intro)
- [SDK API reference](https://developers.rune.ai/docs/multiplayer/api-reference)
- [Supported Games](https://developers.rune.ai/docs/multiplayer/supported-games)
- [Syncing Game State](https://developers.rune.ai/docs/multiplayer/syncing-game-state)

**Comment by bfelbo** [comment]
Thanks for reporting, its been fixed!
