### ISSUE TITLE
Code Assist AI for devs building games with Dusk

### ISSUE THREAD

**Issue by samyakkkk** [rune/rune#459]
Dear maintainers, greetings from [CommandDash](https://commanddash.io)! 

We are a tool to turn docs and examples of your library into a code generation AI agent which **helps devs directly generate code for your library as per their requirements.**

Our team came love what you are building at Dusk and figured it could be helpful for new developers building on it to have one such agent. It's ready and is accessible on: [Web](https://app.commanddash.io/agent?github=https://github.com/dusk-gg/dusk) (Try here!) | [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=WelltestedAI.fluttergpt) 

You can link this in your readme as a badge:

<a href="https://app.commanddash.io/agent?github=https://github.com/dusk-gg/dusk"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA?style=for-the-badge"></a>
```md
<a href="https://app.commanddash.io/agent?github=https://github.com/dusk-gg/dusk"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>
```
Please feel free to mention it if you believe this could be helpful for new users. Or, close the issue if not. 🙏🏻

_The agent is free to use, fully safe (no data retained) and auto-refreshes to stay upto date._

Best wishes!

**Comment by bfelbo** [comment]
Thanks. I tried it with a few simple game examples. It sort of works, but also makes some mistakes, where it doesn't understand the SDK. In it's current state, it might be quite confusing for people new to the SDK.

We'll skip for now, but feel free to ping on this issue when you've improved the code generation :)

**Comment by samyakkkk** [comment]
Hi @bfelbo, thanks for your feedback! 

It would be really helpful if you please help us understand: 
1. What kind of mistakes it made, and 
2. What were the right sources to answer that particular question

We can make the code generation much more accurate with your inputs :)
