### ISSUE TITLE
[Template/Typescript+Vue] Upgrade Dusk dependency to 4.21

### ISSUE THREAD

**Issue by oatspear** [rune/rune#514]
The dependency on Dusk 4.20 in the Typescript+Vue template's `package.json` causes the following import to fail in `vite.config.ts`.

```js
import dusk from "dusk-games-sdk/vite"
```

Upgrading to Dusk 4.21 solves it.

```diff
    "dependencies": {
-     "dusk-games-sdk": "^4.20.2",
+     "dusk-games-sdk": "^4.21.13",
      "vue": "^3.4.29"
    },
```

**Comment by Gongreg** [comment]
Hey @oatspear, I've noticed that and already released a CLI version with fixed dependency: https://github.com/dusk-gg/dusk/blob/staging/packages/dusk-cli/templates/typescript-vue/package.json . Should be in CLI version 7.8.6.
